### ISSUE TITLE
Henüz not yokken arama fonksiyonu hata veriyor

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#1]
```localStorage.clear()``` ile veritabanını temizledikten sonra arama çubuğuna yazmaya başladığımda consoleda 
```TypeError: h.getNotes() is null ``` alıyorum.  

Burada birkaç yöntemle çözebilirsin, aklıma gelenler şunlar:
a - Uygulama ilk açıldığında, eğer istediği veri yapıları bulunmuyorsa, ön tanımlı değerler ile bunları oluşturabilirsin
b -  Fonksiyonlar, sonuç bulunmuyorsa ön tanımlı değerler dönebilirler
c - Fonksiyonlar beklenilen değerleri dönmüyorlarsa, ilerletmeyebilirsin

a - Örneğin: işlemler localStorage'da yer alan notes adında bir array üzerinde dönüyorsa, uygulama açıldığında bu array'ın varlığını kontrol eder, eğer bulamazsa içi boş bir array olarak oluşturur.

b - getNotes eğer array dönmeliyse ve eğer veriyapısında bunu karşılayacak bir şey yoksa, null ya da  undefined dönmek yerine, normalde beklenen yapıda ancak boş içerik dönebilir. Bu her zaman istenilen bir şey değil, ancak uygulamanın işleyişine göre sorunsuz bir çözüm olabilir. 

c - Bu soruna özel olarak chain kısmında getNotes() null değil ise filtrele, null ise hata bildir ya da **a** senaryosunu işlet vb diyebilirsin. Genel bir çözüm olarak, gerçekten sorun verebilecek yerlerde bu kontrolü kullanabilirsin. Ancak her aşamada kontrol gerektirebilecek bir yapıya doğru gidiyorsa, yani if - else / throw - catch  yığınına dönmüşse, temelde bir sorun var demektir.

**Comment by ozansozuozgit** [comment]
a - Örneğin: işlemler localStorage'da yer alan notes adında bir array üzerinde dönüyorsa, uygulama açıldığında bu array'ın varlığını kontrol eder, eğer bulamazsa içi boş bir array olarak oluşturur.

Bu yolu izleyerek sorunu duzelttigime inaniyorum. Tesekkurler
