### ISSUE TITLE
Yeni not ekleme düğmesine basınca, boş bir not oluşturuyor

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#10]
Not oluşturmaksızın, düzenleme popup'ı açılmalı. düzenleme sonrasında save düğmesi ile not -eğer geçerli bir not ise - kaydedilmeli, cancel ile herhangi bir kayıt işlemi olmaksızın popup kapatılmalı.

**Comment by ozansozuozgit** [comment]
Duzenleme yaptim. Kontrol edersen sevinirim. Tesekkurler

**Comment by altunyurt** [comment]
çalışıyor
