### ISSUE TITLE
let - const kullanımı

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#11]
https://github.com/ozansozuozgit/vue-notebook/blob/main/src/services/db_service.js dosyasında let const keywordlerin rastgele kullanımı söz konusu. Anlaşılabilirlik ve izlenebilirlik için bu tanımlayıcıları uygun olarak kullanmaya çalış, değişkenlere ilişkin güncellemelerde tanımlayıcıları da güncelle.  Özetle: değişmeyen değişkeni let olarak tanımlama ve değişkeni tanımladığın bağlama önem ver.

**Comment by ozansozuozgit** [comment]
Duzenleme yaptim. Umarim daha dogru kullanmisimdir. Tesekkurler

**Comment by altunyurt** [comment]
Görece daha iyi .
