### ISSUE TITLE
Kayıtlı notun text kısmını silip kaydet deyince popup kayboluyor

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#12]
Yeniden aynı nota tıklayınca yalnızca siyah arka plan görüntüleniyor. düzenleme popup artık çalışmıyor. sayfayı yenileyince not artık görüntülenmiyor.

**Comment by ozansozuozgit** [comment]
Bu problemi ben tekrar uretemedim. Acaba localstorage sifirlamayi denedin mi? Belki ondan kaynaklaniyor olabilir?

**Comment by altunyurt** [comment]
sıfırladım. tam olarak şunu yapıyorum:

- not oluştur
- kaydet
- notu aç
- düzenle
- bodyi çarpıya basarak sil
- kaydet
hata durumu oluşuyor

**Comment by ozansozuozgit** [comment]
Duzeltildi. Tesekkurler

**Comment by altunyurt** [comment]
çalışıyor
