### ISSUE TITLE
Mobil uyumluluk gerekiyor

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#13]
mobil aygıtlar ile baktığımda, masaüstü görüntünün daraltılmış bir biçimini görüyorum. Genel olarak arama kısmı altındaki kolon boşluğu gereksiz duruyor. tüm görüntüyü notlar için kullanabilirsin

**Comment by ozansozuozgit** [comment]
Duzenleme yaptim umarim daha iyidir
