### ISSUE TITLE
Arama çalışmıyor

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#14]
Arama yaptığımda filtreleme uygulanmıyor. Arama yapmaya başladığımda kıstaslara uygun notların ekranda kalmasını bekliyorum, bütün notlar görünüyor.

**Comment by ozansozuozgit** [comment]
Duzenleme yapildi. Kontrol edersen sevinirim

**Comment by altunyurt** [comment]
çalışıyor
