### ISSUE TITLE
Düzenlemede kaydedilemeyen nota görsel eklenebiliyor

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#17]
Adımlar: 
- not oluştur
- notu düzenle 
- title sil
- görsel ekle 
- kaydet de, uyarı çıksın 
- kaydetmeden kapat
- notu yeniden aç
- görsel görünüyor

**Comment by ozansozuozgit** [comment]
Bu anlasilmasi baya zor bir problemdi. Umarim cozumum yeterlidir.

**Comment by altunyurt** [comment]
çalışıyor
