### ISSUE TITLE
+ tuşunda mode değişiyor 

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#2]
+ tuşuna bastığım zaman dark mode ve light mode arasında geçiş yapıyor. + tuşu not ekleme ile ilgili olarak görünüyor ama beklenmedik bir iş daha yapıyor.

**Comment by ozansozuozgit** [comment]
Eski hosting ile baktiniz galiba. Yenisi buydu: https://vue-notebook.netlify.app/

**Comment by altunyurt** [comment]
Doğrudur. eski adrese bakmışım.
