### ISSUE TITLE
Not listesinin tiled v-cardlar ile oluşturulması

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#3]
Notları v-card nesneleri ile ekranda listele. Arama sonuçları da, tüm notlar da aynı görünümle yan yana ve alt alta v-card nesneleri ile gösterilsin. Not içeriği eğer 150 harften uzunsa "..." ile kesilerek görüntülensin. V-card üzerine tıklandığında popup ile tüm not görüntülensin.

**Comment by ozansozuozgit** [comment]
Duzenlemeri yaptim. Kontrol edersen sevinirim. Tesekkurler

**Comment by altunyurt** [comment]
Çalışıyor
