### ISSUE TITLE
Note ekleme arayüzünün popup olarak oluşturulması

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#4]
Ana listede note ekle düğmesine basınca bir popup açılsın ve note ekleme girdi alanları görüntülensin.

Popup üzerinde cancel ve save butonları olsun. Save dedikten sonra note listeye eklensin, popup kapansın.

**Comment by ozansozuozgit** [comment]
Eklemeleri yaptim. Kontrol edersen sevinirim. Tesekkurler

**Comment by altunyurt** [comment]
çalışıyor
