### ISSUE TITLE
Note düzenleme arayüzünün popup olarak oluşturulması

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#5]
#4 ile aynı arayüz kullanılsın. Herhangi bir notu görüntülerken, note görüntüleme popup'ı üzerinde edit butonuna basıldığında düzenleme popupı açılsın, görüntüleme popupı kapansın. note düzenlendikten sonra kaydedildiğinde popup kapansın. cancel denildiğinde note görüntüleme popupına geri dönülsün.

**Comment by ozansozuozgit** [comment]
Duzenleme yapildi. Kontrol edersen sevinirim. Tesekkurler

**Comment by altunyurt** [comment]
çalışıyor
