### ISSUE TITLE
Note içeriklerinde linkler desteklenmeli

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#6]
Note içine link eklediğim zaman, normal yazı olarak görüntüleniyor. örneğin https://google.com yazdığımda, notu görüntülerken bunun tıklanabilir olmasını istiyorum.

**Comment by ozansozuozgit** [comment]
Duzenleme yaptim.Not goruntulenirken link tiklanabilir. Tesekkurler

**Comment by altunyurt** [comment]
çalışıyor
