### ISSUE TITLE
Note içinde statik görseller desteklenmeli 

### ISSUE THREAD

**Issue by altunyurt** [ozansozuozgit/vue-notebook#7]
Notlara jpg ve png uzantılı dosyalar ekleyebilmeli ve bunları görüntüleyebilmeliyim

**Comment by altunyurt** [comment]
Görsel yüklenebiliyor ve kaydediliyor, ama notu yeniden açtığımda görseli göremiyorum.

**Comment by ozansozuozgit** [comment]
Eklendi

**Comment by altunyurt** [comment]
çalışıyor
